### ISSUE TITLE
Centos hstore problems

### ISSUE THREAD

**Issue by andrewfam** [djangonauts/django-hstore#104]
I'm using Django 1.7 and had working hstore fields on an Ubuntu server.
Recently moved to a Centos7 and using Postgres 9.3

Admin keeps showing 
invalid JSON: SyntaxError: Unexpected token =

Data is as below:
"1"=>"[32, 31, 9, 10, 6, 7, 8]", "8"=>"[9, 10, 6, 7, 8]"

Formatting the data to proper json generates the above again upon save

**Comment by nemesisdesign** [comment]
@andrewfam this is quite hard for me to debug as I don't use CentOS and I cannot verify if this is a misconfiguration or a real bug.

**Comment by nemesisdesign** [comment]
Try to clone this repo, follow the instructions (all the steps) on how to run the unit tests, and report any error.

**Comment by nemesisdesign** [comment]
Closing because no detailed information was provided, if anybody will provide more insights I'll reopen.
