### ISSUE TITLE
django 1.8 support

### ISSUE THREAD

**Issue by nemesisdesign** [djangonauts/django-hstore#105]
Anyone wants to help out?

**Comment by nemesisdesign** [comment]
follow #107

**Comment by 9gix** [comment]
I believed in Django 1.8 has [django.contrib.postgres.fields.HStoreField][1] internally.

[1]: https://docs.djangoproject.com/en/1.8/ref/contrib/postgres/fields/#django.contrib.postgres.fields.HStoreField

**Comment by nemesisdesign** [comment]
@9gix it has but it doesn' have the same features and API of django-hstore, so we'll make a new release that is compatible with django 1.8 and then gradually wrap django's implementation and our additional features on it.

**Comment by nemesisdesign** [comment]
#107 is merged, please test and open new issues if you find any django 1.8 related bug
