### ISSUE TITLE
using __icontains={'foo': 'bar'} behaviour has changed between django versions

### ISSUE THREAD

**Issue by stringfellow** [djangonauts/django-hstore#106]
In django 1.6.x you could use django_hstore to perform `FIELD__icontains={'foo': 'bar'}` -- though this is not explicitly documented, there are cases of use for `__icontains` with strings.

Having upgraded to 1.7, this no longer works, causing an error in the SQL

For test example, see: https://github.com/stringfellow/django-hstore-icontains

**Comment by nemesisdesign** [comment]
hey @stringfellow, thank you for reporting this bug.
It would have been so much easier to review if the failing test case would have been included in a pull request to this issue, rather than in a separate repository.
Could you do that?

Let me know
Federico

**Comment by nemesisdesign** [comment]
is this the test case? Are there other tests?
https://github.com/stringfellow/django-hstore-icontains/blob/master/lookup_test/tests.py#L11

**Comment by nemesisdesign** [comment]
I checked the documentation and the tests, it turns out `icontains` lookups only work when doing text based lookups.

    You can still do classic django "contains" lookups as you would normally do for normal text fields if you were looking for a particular string. In this case, the HSTORE field will be converted to text and the lookup will be performed on all the keys and all the values:

```python
Something.objects.create(data={ 'some_key': 'some crazy Value' })

# classic text lookup (look up for occurence of string in all the keys)
Something.objects.filter(data__contains='crazy')
Something.objects.filter(data__contains='some_key')
# classic case insensitive text looup
Something.objects.filter(data__icontains='value')
Something.objects.filter(data__icontains='SOME_KEY')
```

http://djangonauts.github.io/django-hstore/#_python_api

If you think you've found a bug, send a failing test. If you want to add a new feature, open send a pull request.

**Comment by stringfellow** [comment]
Hiya, yes - sorry I'm not entirely sure why I chose to make a separate repo (was pretty tired I think... )
The reason I classed it as 'bug' rather than 'feature' is only because the behaviour changed between versions (i.e. before, regardless of what the docs said, it accepted a dict for an `__icontains` lookup). Anyway, thanks for looking into it and sorry for misunderstanding the docs!

**Comment by nemesisdesign** [comment]
no problem, remember we are open for improvements, one of the things I'd like to put on the roadmap is making django-hstore API compatible with django 1.8's HStoreField, but at the same time providing the additional features of django-hstore.
