### ISSUE TITLE
create() fails (using model with slug PK) with passed dict

### ISSUE THREAD

**Issue by stringfellow** [djangonauts/django-hstore#111]
With `SerializedDictionaryField` using `create(data={'foo': 1})` fails if using a model with a non auto-id (e.g. slug)

**Comment by nemesisdesign** [comment]
@alukach this issue was related to SerializedDictionaryField, I had to introduce this little change to fix it: https://github.com/djangonauts/django-hstore/commit/c3f3142e6bf9d82d5e91e4353033b09b712f0397

Could you check it out when you have time and let me know if all is ok?

**Comment by alukach** [comment]
Absolutely, will take a look shortly.

**Comment by alukach** [comment]
Have we been able to verify this bug?  Looking at [this test](https://github.com/djangonauts/django-hstore/blob/5e403bf469ac8fe8e4c3d9d08f05c79e47662296/tests/django_hstore_tests/tests/test_serialized_dictionary_field.py#L56-L58):

``` python
    def test_create_directly(self):
        SerializedDataBag.objects.create(name='abc', data={'num': 1})
        SerializedDataBagNoID.objects.create(slug='123', name='abc', data={'num': 1})
```

[The models](https://github.com/djangonauts/django-hstore/blob/5e403bf469ac8fe8e4c3d9d08f05c79e47662296/tests/django_hstore_tests/models.py#L40-L48) are as such:

``` python
class SerializedDataBag(HStoreModel):
    name = models.CharField(max_length=32)
    data = hstore.SerializedDictionaryField()


class SerializedDataBagNoID(HStoreModel):
    slug = models.SlugField(primary_key=True)
    name = models.CharField(max_length=32)
    data = hstore.SerializedDictionaryField()
```

Wouldn't this condition be caught by `SerializedDataBag.objects.create(name='abc', data={'num': 1})`? What's different?

**Comment by alukach** [comment]
Ah, okay, I now see that the `test_create_directly` test was created to illustrate this bug and that @nemesisdesign's fix was merged.

All looks good to me!

**Comment by nemesisdesign** [comment]
thx @alukach
