### ISSUE TITLE
zc.buildout cannot install version 1.3.7

### ISSUE THREAD

**Issue by emorozov** [djangonauts/django-hstore#116]
Version 1.3.7 of the django-hstore cannot be installed via buildout. It always fails with the following error:
```
Getting distribution for 'django-hstore==1.3.7'.
While:
  Installing django.
  Getting distribution for 'django-hstore==1.3.7'.
Error: Couldn't find a distribution for 'django-hstore==1.3.7'.
```

I guess distribution format has changed in 1.3.7 and buildout is not compatible with it. Can some compatibility distribution be added for the buildout?

**Comment by nemesisdesign** [comment]
Replicated issue with:

    pip install --no-use-wheel django_hstore==1.3.7

Next time something like this happens try this:

    pip install -U pip wheel setuptools
    pip install <package>

I had to upload the source distribution again on pypi with a different name. It should be fixed now.
Let me know.
