### ISSUE TITLE
Using F() expressions?

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [djangonauts/django-hstore#119]
Is it possible to use F() expressions to update an HStore field? I want to have a "stats" field in my models, for collected statistics of the model... for instance:

class State(model.Model):
    name = models.CharField()
    stats = HStoreField(default={"cities_count": 0}

I want the stats->cities_count incremented using an F() expression whenever a City is added to the State... does anyone know how to achieve this?

thank you!

**Comment by nemesisdesign** [comment]
Hi @DanielFerreiraJorge, i sincerely don't know because I have not tried `F()` expressions yet.

**Comment by nemesisdesign** [comment]
For further questions, use the discussion group: https://groups.google.com/forum/#!forum/django-hstore
