### ISSUE TITLE
Django 1.9 and EmptyShortCircuit deprecated

### ISSUE THREAD

**Issue by aidanlister** [djangonauts/django-hstore#132]
Here's the commit where it's removed:
https://github.com/django/django/commit/4d3470e52e005ed75aa6c7d4204bf5ca87733f85

**Comment by nemesisdesign** [comment]
Will be closed by #133

**Comment by nemesisdesign** [comment]
Try the latest master and let me know if it works so we can close this and move on.

**Comment by aidanlister** [comment]
I'm a little worried about replacing EmptyShortCircuit with Exception ... what's it meant to be?

**Comment by nemesisdesign** [comment]
It's the best short term solution we can think of. Please test it and report any problems or suggest an alternative solution. Read #133 for more info.

**Comment by 23doors** [comment]
It seems to be working fine although it seems pretty dirty. Any eta on updating pypi version?
Anyway. Instead of potentially hiding some process() issues by reraising a different exception in 1.9, it would be better to just do not catch anything there or at least reraise original exception.

**Comment by nemesisdesign** [comment]
Feel free to send a pull request with a solution you think works better.

**Comment by 23doors** [comment]
Sure. But are there any chances of pushing what we got now to pypi any time soon? It may not be super pretty but it does the job.

**Comment by nemesisdesign** [comment]
@23doors I released 1.4.1 yesterday
