### ISSUE TITLE
Update HStoreWhereNode to follow django's WhereNode

### ISSUE THREAD

**Issue by jarekwg** [djangonauts/django-hstore#135]
The Constraint class has been deprecated since django17 and was removed in django19 (django/django@5008a4) in favour of the Lookup class, which was introduced in django17 (django/django@20bab2).

Consequently django's WhereNode class looks very different now than it used to and HStoreWhereNode needs to be rewritten to follow suit.

Required action:
-Update HStoreWhereNode to behave like WhereNode in django19, ensuring backward compatibility down to django17.
-Drop django16 support.

**Comment by nemesisdesign** [comment]
Closing this as #133 was merged
