### ISSUE TITLE
1.4.1 regression: TypeError: Decimal is not JSON serializable

### ISSUE THREAD

**Issue by prokaktus** [djangonauts/django-hstore#144]
Hello!

This issue introduced by commit 3b235cb9dfe6a197179399cc63d115003ea71f62.

django-hstore version: 1.4.1
django version: 1.7
python version: 2.7.6

**Problem description:**
My model have field `hstore.DictionaryField`. Before 1.4.1, in method `ensure_acceptable_value`, code
https://github.com/djangonauts/django-hstore/blob/3b235cb9dfe6a197179399cc63d115003ea71f62/django_hstore/dict.py#L123
```
            ...
            elif isinstance(value, (list, dict)):
                return force_text(json.dumps(value))
           ...
```
works well with `Decimal` objects in lists, because `simplejson` supports dumps for `Decimals`. But  standard python `json` not. Because of that I get `TypeError: Decimal('10') is not JSON serializable
`

**Comment by nemesisdesign** [comment]
Please send a failing test with a patch.

**Comment by prokaktus** [comment]
Now it can be closed.

**Comment by nemesisdesign** [comment]
Thank you @prokaktus
