### ISSUE TITLE
GrappelliAdminHStoreWidget - Deleting elements doesn't work properly inside StackedInline

### ISSUE THREAD

**Issue by jcalazan** [djangonauts/django-hstore#146]
django==1.8
django-hstore==1.4.1
django-grappelli==2.7.3

Only a problem with StackedInline.

To reproduce:

1. Add inline object.
2. Add a 2 elements in the hstore.DictionaryField
3. Save
4. Click one of the `-` (remove) icon -> instead of just deleting 1 element, all elements got deleted instead.  And then when you add another inline object and hit save, a ValidationError occurs complaining about `value must be an integer` during `full_clean()` (looks like a missing pk).

**Comment by nemesisdesign** [comment]
It's a documented known issue:

**The admin widget will work with inlines only if using StackedInline. It won’t work on TabularInline.**

http://djangonauts.github.io/django-hstore/#_limitations

**Comment by jcalazan** [comment]
@nemesisdesign I'm actually using StackedInline and seems to work fine except when deleting existing hstore elements.

**Comment by jcalazan** [comment]
Also, only a problem with the Grappelli widget, the Default admin widget doesn't have the same issue.

**Comment by nemesisdesign** [comment]
If you fix it send a patch.
