### ISSUE TITLE
Broken links for admin in Django 1.9

### ISSUE THREAD

**Issue by gpip** [djangonauts/django-hstore#148]
At `templates/hstore_default_widget.html` django_hstore links to `admin/img/icon_addlink.gif` and others, but Django 1.9 replaced those by svg ones.

For instance, in django_hstore you'll find `<img src="{{ STATIC_URL }}admin/img/icon_addlink.gif" width="10" height="10" alt="{% trans 'Add Another' %}">`

While Django expects something closer to `<img src="{% static 'admin/img/icon-addlink.svg' %}" alt="{% trans 'Add Another' %}"/>`

**Comment by nemesisdesign** [comment]
Thx for reporting, send a patch if you can.

**Comment by nemesisdesign** [comment]
Closed by #149 and 9ed1804
