### ISSUE TITLE
Documentation for old versions

### ISSUE THREAD

**Issue by dangayle** [djangonauts/django-hstore#155]
Is there a way to get to the documentation for the older versions?

**Comment by MattHardcastle** [comment]
You can get the documentation, going back to version 1.2.5, in the doc directory at the commit that was tagged for that release. For example, [docs](https://github.com/djangonauts/django-hstore/tree/1.2.5/doc) is the documentation for version 1.2.5.

As far as I can tell github.io, the hosting platform for django-hstore's documentation, doesn't have a way of referring to previous versions of the site, so you're probably not going to find the HTML output of the documentation without building it yourself.

**Comment by dangayle** [comment]
Ok, thanks.

**Comment by nemesisdesign** [comment]
I would like to convert the docs to sphinx in order to publish it on readthedocs.org, so we can have this feature, but I have no time to do this. If anyone is interested to help me out let me know.

**Comment by MattHardcastle** [comment]
I can take a stab at it @nemesisdesign. The conversion from _asciidoc_ to _restructed_ should be simple enough.
