### ISSUE TITLE
Why forcing DatetimeField to utcnow() ?

### ISSUE THREAD

**Issue by oleiade** [djangonauts/django-hstore#82]
Hi!

We've started using your library @komoot and we've rapidly hit the problem that it is impossible to give a ``None`` value to a ``DateTimeField`` in schema mode.

This part of the code: https://github.com/djangonauts/django-hstore/blob/c5d9b46fa6a678e864c32ed29ee63e37f26df3ca/django_hstore/virtual.py#L102

Seems to indicate that any default value set to ``None`` will be converted to ``datetime.utcnow()``. Is there a reason for this specific behavior? If I'm not mistaken django ORM authorizes ``None`` values for ``DateTimeField`` if ``null=True``.

Our workaround for now is to set ``'kwargs': {'default': ''}``, however it forces our schema to be in a quiet inconsistent state...

Thanks for your explanation :-)

**Comment by nemesisdesign** [comment]
how can we produce a failing test case?

**Comment by nemesisdesign** [comment]
@oleiade @daaray check out the latest changes on master (1.3.6 alpha), it would be very helpful if you could test them on your environment and provide feedback.

**Comment by nemesisdesign** [comment]
Will close this in 1 week if no feedback.
