### ISSUE TITLE
Is there a way to reload schema just for one instance?

### ISSUE THREAD

**Issue by bsod90** [djangonauts/django-hstore#83]
Hi django-hstore developers!

I'm wondering if there is a way to apply schema not to the whole model class, but rather for one model instance.

My situation is following:

I have a model that has a set of fields that are common for all instances.
This model has a 'category'.
Depending on category (e.g. Hotel, Parking, Theatre) I'd like to add a fixed set of additional attributes (different for every category). For example, Hotel should have a star_rating, while Parking should have a lots_number but it shouldn't have a star_rating.
I can't create separate models for each category, I'd like it to be as much dynamic as possible.

So, the solution I see is to attach schema name to a Category model and then apply this schema to 'attributes' field on instance creation. 
However, if I do it in the way described in docs:

```
field = SchemaDataBag._meta.get_field('data')
# load a different schema
field.reload_schema([
    {
        'name': 'url',
        'class': 'URLField'
    }
])
# turn off schema mode
field.reload_schema(None)
```

Schema is getting updated for the whole model class (all instances).

**Comment by nemesisdesign** [comment]
Thank you for the insights, I'm closing this to cleanup the issue list.
