### ISSUE TITLE
update_query breaks transactions in django 1.7

### ISSUE THREAD

**Issue by drag0nius** [djangonauts/django-hstore#84]
*django_hstore.query.update_query* uses *transaction.is_managed* which was completely deprecated in Django 1.7, rendering whole HStoreManager incompatbile with new transaction management.

Basically in 1.7 *transaction.is_managed* does not do or return anything and following code:

    if not transaction.is_managed(using=self.db):
            transaction.enter_transaction_management(using=self.db)

always tries to enter transaction management even if it's already inside atomic block.

The result is:

    django.db.transaction.TransactionManagementError: This is forbidden when an 'atomic' block is active.

EDIT:
*transaction.commit_unless_managed* is used there too and is also deprecated.

**Comment by nemesisdesign** [comment]
so any test case?

**Comment by nemesisdesign** [comment]
@drag0nius did you mean there were actual breakages or did you mean you saw deprecation warnings that need to be fixed to be compatible with the upcoming django 1.8 release?

Could you clarify please?

**Comment by drag0nius** [comment]
@nemesisdesign Yes, django_hstore uses the code which is already deprecated (but not yet completely removed) in 1.7 resulting in breakages.

This is whole source code of [transaction.is_managed()](https://github.com/django/django/blob/stable/1.7.x/django/db/transaction.py#L112-114):
```python
def is_managed(using=None):
    warnings.warn("'is_managed' is deprecated.",
        RemovedInDjango18Warning, stacklevel=2)
```
Then there is [this](https://github.com/djangonauts/django-hstore/blob/master/django_hstore/query.py#L57-59) :
```python
    if not transaction.is_managed(using=self.db):  # always returns true
        transaction.enter_transaction_management(using=self.db)  # this line breaks any kind of transaction.atomic() call there could be
        forced_managed = True
```

**Comment by nemesisdesign** [comment]
@drag0nius, thank you for the explaination.
I need a bit more of guidance, please could you explain the general steps to reproduce the issues on the interactive shell?

Eg:

```
./manage.py shell
```

Then...

```python
from tests.django_hstore_tests.models import SchemaDataBag

bag = SchemaDataBag()
bag.name = 'test'
# ecc...
```

If I had this information I could reproduce the issue and study it more in detail.

**Comment by drag0nius** [comment]
```python
    def test_hupdate_atomic(self):
        if hasattr(transaction, 'atomic'):
            with transaction.atomic():
                self.test_hupdate()
```

**Comment by nemesisdesign** [comment]
Thank you @drag0nius, what python, django and django-hstore versions are you using?

The test you supplied passes and I believe there is already a similar test here:
https://github.com/djangonauts/django-hstore/blob/1afca6e9e95cebc8c65661f7df189856bb9b8bad/tests/django_hstore_tests/tests.py#L967
Do you reckon?

I've tested on:
  * python2.7, django 1.7 and django-hstore master
  * python3.4, django 1.7 and django-hstore master

Federico

**Comment by drag0nius** [comment]
The test you linked uses neither `hupadte()` nor `hremove()`, those 2 are breaking.

I honestly don't see how could it pass from withing transaction.atomic() block, `hupdate()` and `hremove()` are decorated with `update_query()` then it goes like this:

1. https://github.com/djangonauts/django-hstore/blob/master/django_hstore/query.py#L58
2. https://github.com/django/django/blob/stable/1.7.x/django/db/transaction.py#L74
3. https://github.com/django/django/blob/stable/1.7.x/django/db/backends/__init__.py#L301
4. https://github.com/django/django/blob/stable/1.7.x/django/db/backends/__init__.py#L380

There is just no way it could pass.

Tomorrow i'll try doing tests myself.

**Comment by nemesisdesign** [comment]
I just pushed the test case: https://github.com/djangonauts/django-hstore/commit/cb6830a9475ca124c19552d7625456b2ef76373a
Which unfortunately doesn't replicate any bug.
Please send a failing test case.
