### ISSUE TITLE
How can I use "update()", not "save()" with hstore field?

### ISSUE THREAD

**Issue by pashinin** [djangonauts/django-hstore#88]
I'm looking for something like:
```
Model.objects.filter(pk=f.id).update(debug__v=v)
```

Where `debug` is a hstore field, and `__v` is a key: `debug["v"]`.
I'm looking for this because I want to update hstore field, but do not call `post_save` functions. (in case of `save()`)

**Comment by nemesisdesign** [comment]
Not possible currently.
