### ISSUE TITLE
Liskov Violation in `HStoreDict`

### ISSUE THREAD

**Issue by skatenerd** [djangonauts/django-hstore#95]
First off, I am using this library with `schema_mode` turned off.

Now, it is very likely that my code will have the built-in assumption that, 

For all `x`
If `isinstance(d, dict)`, 
and I type `d["hi"] = x`
then `d["hi"] == x`

This is guaranteed in general by dictionaries, but not by `HStoreDict` (since everything gets converted to strings).  This can cause very [subtle errors](http://en.wikipedia.org/wiki/Liskov_substitution_principle#A_typical_violation).

In my case, the [Voluptuous library](https://pypi.python.org/pypi/voluptuous/) was failing to properly coerce strings to floats, because it was consuming an `HStoreDict`.  The workaround is just to convert my `HStoreDict` back to a standard `dict` before passing it on to Voluptuous.

I am not sure if there is a sensible way to fix this problem.  I imagine that the this behavior exists because the `hstore` column stores only strings; if they are going to have to be saved in the DB as strings, we might as well get that work done as early as possible.

Perhaps we could move to a strategy where we convert values to strings on save, rather than on dictionary-update?  Or maybe we could raise an exception if you try to insert a non-string into the dictionary?

**Comment by alukach** [comment]
I'm not entirely clear as to why passing an `HStoreDict` object to Voluptuous fails while a standard `dict` does not (I know very little of Voluputuous, this is the first I've heard of it).

Nonetheless, I opened a pull request a while ago to create a field to automatically serialize/deserialize values upon input/output.  This would maintain datatype (for any common standard python datatype), which I do believe would solve the issue you raised.  You can take a look at the pull requests here: https://github.com/djangonauts/django-hstore/pull/80

**Comment by skatenerd** [comment]
Voluptuous inspects the type of whatever you handed it, and tries to give you a new instance of the same type:
https://github.com/alecthomas/voluptuous/blob/master/voluptuous.py#L501
https://github.com/alecthomas/voluptuous/blob/master/voluptuous.py#L682

I am using Voluptuous to *coerce* items, which is pretty meaningless when you re-insert a coerced item back into a casts-everything-to-string datastructure.

Your PR looks awesome; I especially like the ability to query on the *casted* values (`lt`, `gt`, etc).  For now, I am using a similar pattern - just wrapping query results in objects which know how to coerce the values that they contain.

**Comment by alukach** [comment]
You could also lean on this mixin that I made: https://bitbucket.org/ospreyinformatics/django-hstore-mixin/ .  It's not ideal but it works well enough (I use it on a few projects).  It's what led me to make that PR.  The goal is that, once that PR goes through, this mixin will be obsolete and all the data in the DB will be serialized, making it compatible with the new `SerializedDictionaryField`.

**Comment by nemesisdesign** [comment]
This is by design. If you need a different behaviour follow this pull request and send feedback or contribute in any way you can: https://github.com/djangonauts/django-hstore/pull/80

Best regards
Federico
